# Generated by Django 3.0.8 on 2020-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200717_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupproject',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='startupproject',
            name='slack',
            field=models.CharField(max_length=30),
        ),
    ]
