# Generated by Django 3.0.8 on 2020-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_startupproject_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.TextField(verbose_name='Xотим в командy'),
        ),
    ]
