# Generated by Django 3.0.8 on 2020-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200718_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Имя соискателя')),
                ('about_message', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('slack', models.CharField(max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='startupproject',
            name='project_type',
            field=models.CharField(default='startup', max_length=8, verbose_name='Тип проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupproject',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения'),
        ),
    ]
